//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/PlayerControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControl"",
    ""maps"": [
        {
            ""name"": ""PlayerControllers"",
            ""id"": ""95154a0c-2bf6-473e-974c-f09bcf2c7531"",
            ""actions"": [
                {
                    ""name"": ""Forward"",
                    ""type"": ""Button"",
                    ""id"": ""dc111daf-675d-4165-8aae-0cf576409e2f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sideward"",
                    ""type"": ""Button"",
                    ""id"": ""979115d2-d57a-4ccd-9a87-e498b339bdca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Roll"",
                    ""type"": ""Button"",
                    ""id"": ""35078537-3df2-4ae4-9b1f-561f406f413a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0a4cfcd6-a839-4721-b877-555c989a0519"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29af148a-eb3b-4cc1-9d47-b311e3c61c8d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sideward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""48c088e5-52ed-4456-978e-514da575e029"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sideward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3fae1d5-81b4-499a-ac9e-c01ee7c5cdc3"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Controls_Fruit_Drop"",
            ""id"": ""2b850db2-aa4d-468f-8d5c-e54852dca253"",
            ""actions"": [
                {
                    ""name"": ""Walk P1"",
                    ""type"": ""Button"",
                    ""id"": ""221d9bd7-f2ba-4794-82b7-c983c2fa4cda"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump P1"",
                    ""type"": ""Button"",
                    ""id"": ""4a072253-ba53-4062-8a67-783821056fe8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Walk P2"",
                    ""type"": ""Button"",
                    ""id"": ""a215bc16-728a-4da5-a4fd-6c8a8d4194a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump P2"",
                    ""type"": ""Button"",
                    ""id"": ""7d425fbc-dd45-4e57-9b64-6f02a4708a95"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Walk P1"",
                    ""id"": ""1332b39d-df30-4522-97b4-0a7f3c579d5b"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk P1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""161903e5-12ad-4765-be7f-80d57a8331ef"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk P1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ee988748-5801-4570-87ff-9063bf8a0afe"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk P1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6cb463ac-2323-4a1c-afa4-7d5377e16c1e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump P1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Walk P2"",
                    ""id"": ""49837c70-557e-4c7d-be66-97d3a1e9f912"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk P2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""9458a791-72cd-4483-b2ba-d492376f0c48"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk P2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""25928633-f58a-4649-b363-faad8a8d1cf9"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk P2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8d3f8a4a-cca6-4579-9c25-7eec0c0edffa"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump P2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerControllers
        m_PlayerControllers = asset.FindActionMap("PlayerControllers", throwIfNotFound: true);
        m_PlayerControllers_Forward = m_PlayerControllers.FindAction("Forward", throwIfNotFound: true);
        m_PlayerControllers_Sideward = m_PlayerControllers.FindAction("Sideward", throwIfNotFound: true);
        m_PlayerControllers_Roll = m_PlayerControllers.FindAction("Roll", throwIfNotFound: true);
        // Controls_Fruit_Drop
        m_Controls_Fruit_Drop = asset.FindActionMap("Controls_Fruit_Drop", throwIfNotFound: true);
        m_Controls_Fruit_Drop_WalkP1 = m_Controls_Fruit_Drop.FindAction("Walk P1", throwIfNotFound: true);
        m_Controls_Fruit_Drop_JumpP1 = m_Controls_Fruit_Drop.FindAction("Jump P1", throwIfNotFound: true);
        m_Controls_Fruit_Drop_WalkP2 = m_Controls_Fruit_Drop.FindAction("Walk P2", throwIfNotFound: true);
        m_Controls_Fruit_Drop_JumpP2 = m_Controls_Fruit_Drop.FindAction("Jump P2", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerControllers
    private readonly InputActionMap m_PlayerControllers;
    private List<IPlayerControllersActions> m_PlayerControllersActionsCallbackInterfaces = new List<IPlayerControllersActions>();
    private readonly InputAction m_PlayerControllers_Forward;
    private readonly InputAction m_PlayerControllers_Sideward;
    private readonly InputAction m_PlayerControllers_Roll;
    public struct PlayerControllersActions
    {
        private @PlayerControl m_Wrapper;
        public PlayerControllersActions(@PlayerControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @Forward => m_Wrapper.m_PlayerControllers_Forward;
        public InputAction @Sideward => m_Wrapper.m_PlayerControllers_Sideward;
        public InputAction @Roll => m_Wrapper.m_PlayerControllers_Roll;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControllers; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControllersActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerControllersActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerControllersActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerControllersActionsCallbackInterfaces.Add(instance);
            @Forward.started += instance.OnForward;
            @Forward.performed += instance.OnForward;
            @Forward.canceled += instance.OnForward;
            @Sideward.started += instance.OnSideward;
            @Sideward.performed += instance.OnSideward;
            @Sideward.canceled += instance.OnSideward;
            @Roll.started += instance.OnRoll;
            @Roll.performed += instance.OnRoll;
            @Roll.canceled += instance.OnRoll;
        }

        private void UnregisterCallbacks(IPlayerControllersActions instance)
        {
            @Forward.started -= instance.OnForward;
            @Forward.performed -= instance.OnForward;
            @Forward.canceled -= instance.OnForward;
            @Sideward.started -= instance.OnSideward;
            @Sideward.performed -= instance.OnSideward;
            @Sideward.canceled -= instance.OnSideward;
            @Roll.started -= instance.OnRoll;
            @Roll.performed -= instance.OnRoll;
            @Roll.canceled -= instance.OnRoll;
        }

        public void RemoveCallbacks(IPlayerControllersActions instance)
        {
            if (m_Wrapper.m_PlayerControllersActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerControllersActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerControllersActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerControllersActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerControllersActions @PlayerControllers => new PlayerControllersActions(this);

    // Controls_Fruit_Drop
    private readonly InputActionMap m_Controls_Fruit_Drop;
    private List<IControls_Fruit_DropActions> m_Controls_Fruit_DropActionsCallbackInterfaces = new List<IControls_Fruit_DropActions>();
    private readonly InputAction m_Controls_Fruit_Drop_WalkP1;
    private readonly InputAction m_Controls_Fruit_Drop_JumpP1;
    private readonly InputAction m_Controls_Fruit_Drop_WalkP2;
    private readonly InputAction m_Controls_Fruit_Drop_JumpP2;
    public struct Controls_Fruit_DropActions
    {
        private @PlayerControl m_Wrapper;
        public Controls_Fruit_DropActions(@PlayerControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @WalkP1 => m_Wrapper.m_Controls_Fruit_Drop_WalkP1;
        public InputAction @JumpP1 => m_Wrapper.m_Controls_Fruit_Drop_JumpP1;
        public InputAction @WalkP2 => m_Wrapper.m_Controls_Fruit_Drop_WalkP2;
        public InputAction @JumpP2 => m_Wrapper.m_Controls_Fruit_Drop_JumpP2;
        public InputActionMap Get() { return m_Wrapper.m_Controls_Fruit_Drop; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Controls_Fruit_DropActions set) { return set.Get(); }
        public void AddCallbacks(IControls_Fruit_DropActions instance)
        {
            if (instance == null || m_Wrapper.m_Controls_Fruit_DropActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Controls_Fruit_DropActionsCallbackInterfaces.Add(instance);
            @WalkP1.started += instance.OnWalkP1;
            @WalkP1.performed += instance.OnWalkP1;
            @WalkP1.canceled += instance.OnWalkP1;
            @JumpP1.started += instance.OnJumpP1;
            @JumpP1.performed += instance.OnJumpP1;
            @JumpP1.canceled += instance.OnJumpP1;
            @WalkP2.started += instance.OnWalkP2;
            @WalkP2.performed += instance.OnWalkP2;
            @WalkP2.canceled += instance.OnWalkP2;
            @JumpP2.started += instance.OnJumpP2;
            @JumpP2.performed += instance.OnJumpP2;
            @JumpP2.canceled += instance.OnJumpP2;
        }

        private void UnregisterCallbacks(IControls_Fruit_DropActions instance)
        {
            @WalkP1.started -= instance.OnWalkP1;
            @WalkP1.performed -= instance.OnWalkP1;
            @WalkP1.canceled -= instance.OnWalkP1;
            @JumpP1.started -= instance.OnJumpP1;
            @JumpP1.performed -= instance.OnJumpP1;
            @JumpP1.canceled -= instance.OnJumpP1;
            @WalkP2.started -= instance.OnWalkP2;
            @WalkP2.performed -= instance.OnWalkP2;
            @WalkP2.canceled -= instance.OnWalkP2;
            @JumpP2.started -= instance.OnJumpP2;
            @JumpP2.performed -= instance.OnJumpP2;
            @JumpP2.canceled -= instance.OnJumpP2;
        }

        public void RemoveCallbacks(IControls_Fruit_DropActions instance)
        {
            if (m_Wrapper.m_Controls_Fruit_DropActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IControls_Fruit_DropActions instance)
        {
            foreach (var item in m_Wrapper.m_Controls_Fruit_DropActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Controls_Fruit_DropActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Controls_Fruit_DropActions @Controls_Fruit_Drop => new Controls_Fruit_DropActions(this);
    public interface IPlayerControllersActions
    {
        void OnForward(InputAction.CallbackContext context);
        void OnSideward(InputAction.CallbackContext context);
        void OnRoll(InputAction.CallbackContext context);
    }
    public interface IControls_Fruit_DropActions
    {
        void OnWalkP1(InputAction.CallbackContext context);
        void OnJumpP1(InputAction.CallbackContext context);
        void OnWalkP2(InputAction.CallbackContext context);
        void OnJumpP2(InputAction.CallbackContext context);
    }
}
